### ISSUE TITLE
suggestion: sqlite

### ISSUE THREAD

**Issue by persianphilosopher** [rocboss/batio#1]
Hi there,
I am glad to this project. I have been looking for something that integrates Flight, Medoo, Auth!
Since you have Medoo, may I suggest providing the option to work with sqlite as well? For micro php projects, it's very helpful to be able to use sqlite. 
Thanks for sharing this project!

**Comment by rocboss** [comment]
Um, I will consider this option. If you want to use it now, you could add a configuration item to the `.env` file, and use `Medoo` flexibly as you want.

**Comment by persianphilosopher** [comment]
Thanks for considering it. I did make it work that exact way. I was suggesting it as a small added feature for those who may not want/know how to do that.
Best
